Forgotten_Cave_Entrance_MapScripts::
	.byte 0


AncientText1::
	lock
	msgbox AncientText1_Text_0
	release
	end


AncientText2::
	lock
	msgbox AncientText2_Text_0
	release
	end


AncientText3::
	lock
	msgbox AncientText3_Text_0
	release
	end


AncientText1_Text_0:
	.string "In ... land of ...isue the Al...hty Sin...h,\n"
	.string "the Orig...ne, cr...ted bei... of ti..., ...ace\l"
	.string "and distor...$"

AncientText2_Text_0:
	.string "Wit...em, tim... space d...orting artif...s\n"
	.string "cam... be.$"

AncientText3_Text_0:
	.string "Nine ...tifacts rest ... They ... possible\n"
	.string "...teract with beings of m...$"
